# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/quic-art

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/quic-art

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/quic-art/CMakeFiles /home/ubuntu/quic-art//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/quic-art/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named http_server

# Build rule for target.
http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_server
.PHONY : http_server

# fast build rule for target.
http_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/http_server.dir/build.make bin/CMakeFiles/http_server.dir/build
.PHONY : http_server/fast

#=============================================================================
# Target rules for targets named art_server

# Build rule for target.
art_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 art_server
.PHONY : art_server

# fast build rule for target.
art_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/art_server.dir/build.make bin/CMakeFiles/art_server.dir/build
.PHONY : art_server/fast

#=============================================================================
# Target rules for targets named md5_server

# Build rule for target.
md5_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md5_server
.PHONY : md5_server

# fast build rule for target.
md5_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/md5_server.dir/build.make bin/CMakeFiles/md5_server.dir/build
.PHONY : md5_server/fast

#=============================================================================
# Target rules for targets named md5_client

# Build rule for target.
md5_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md5_client
.PHONY : md5_client

# fast build rule for target.
md5_client/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/md5_client.dir/build.make bin/CMakeFiles/md5_client.dir/build
.PHONY : md5_client/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/echo_server.dir/build.make bin/CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named echo_client

# Build rule for target.
echo_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_client
.PHONY : echo_client

# fast build rule for target.
echo_client/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/echo_client.dir/build.make bin/CMakeFiles/echo_client.dir/build
.PHONY : echo_client/fast

#=============================================================================
# Target rules for targets named duck_server

# Build rule for target.
duck_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 duck_server
.PHONY : duck_server

# fast build rule for target.
duck_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/duck_server.dir/build.make bin/CMakeFiles/duck_server.dir/build
.PHONY : duck_server/fast

#=============================================================================
# Target rules for targets named duck_client

# Build rule for target.
duck_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 duck_client
.PHONY : duck_client

# fast build rule for target.
duck_client/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/duck_client.dir/build.make bin/CMakeFiles/duck_client.dir/build
.PHONY : duck_client/fast

#=============================================================================
# Target rules for targets named perf_client

# Build rule for target.
perf_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_client
.PHONY : perf_client

# fast build rule for target.
perf_client/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/perf_client.dir/build.make bin/CMakeFiles/perf_client.dir/build
.PHONY : perf_client/fast

#=============================================================================
# Target rules for targets named perf_server

# Build rule for target.
perf_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_server
.PHONY : perf_server

# fast build rule for target.
perf_server/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/perf_server.dir/build.make bin/CMakeFiles/perf_server.dir/build
.PHONY : perf_server/fast

#=============================================================================
# Target rules for targets named http_client

# Build rule for target.
http_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_client
.PHONY : http_client

# fast build rule for target.
http_client/fast:
	$(MAKE) $(MAKESILENT) -f bin/CMakeFiles/http_client.dir/build.make bin/CMakeFiles/http_client.dir/build
.PHONY : http_client/fast

#=============================================================================
# Target rules for targets named lsquic

# Build rule for target.
lsquic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsquic
.PHONY : lsquic

# fast build rule for target.
lsquic/fast:
	$(MAKE) $(MAKESILENT) -f src/liblsquic/CMakeFiles/lsquic.dir/build.make src/liblsquic/CMakeFiles/lsquic.dir/build
.PHONY : lsquic/fast

#=============================================================================
# Target rules for targets named test_ack

# Build rule for target.
test_ack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ack
.PHONY : test_ack

# fast build rule for target.
test_ack/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ack.dir/build.make tests/CMakeFiles/test_ack.dir/build
.PHONY : test_ack/fast

#=============================================================================
# Target rules for targets named test_ackgen_gquic_be

# Build rule for target.
test_ackgen_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ackgen_gquic_be
.PHONY : test_ackgen_gquic_be

# fast build rule for target.
test_ackgen_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ackgen_gquic_be.dir/build.make tests/CMakeFiles/test_ackgen_gquic_be.dir/build
.PHONY : test_ackgen_gquic_be/fast

#=============================================================================
# Target rules for targets named test_ackparse_gquic_be

# Build rule for target.
test_ackparse_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ackparse_gquic_be
.PHONY : test_ackparse_gquic_be

# fast build rule for target.
test_ackparse_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ackparse_gquic_be.dir/build.make tests/CMakeFiles/test_ackparse_gquic_be.dir/build
.PHONY : test_ackparse_gquic_be/fast

#=============================================================================
# Target rules for targets named test_ackparse_ietf

# Build rule for target.
test_ackparse_ietf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ackparse_ietf
.PHONY : test_ackparse_ietf

# fast build rule for target.
test_ackparse_ietf/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ackparse_ietf.dir/build.make tests/CMakeFiles/test_ackparse_ietf.dir/build
.PHONY : test_ackparse_ietf/fast

#=============================================================================
# Target rules for targets named test_alarmset

# Build rule for target.
test_alarmset: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_alarmset
.PHONY : test_alarmset

# fast build rule for target.
test_alarmset/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_alarmset.dir/build.make tests/CMakeFiles/test_alarmset.dir/build
.PHONY : test_alarmset/fast

#=============================================================================
# Target rules for targets named test_alt_svc_ver

# Build rule for target.
test_alt_svc_ver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_alt_svc_ver
.PHONY : test_alt_svc_ver

# fast build rule for target.
test_alt_svc_ver/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_alt_svc_ver.dir/build.make tests/CMakeFiles/test_alt_svc_ver.dir/build
.PHONY : test_alt_svc_ver/fast

#=============================================================================
# Target rules for targets named test_arr

# Build rule for target.
test_arr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_arr
.PHONY : test_arr

# fast build rule for target.
test_arr/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_arr.dir/build.make tests/CMakeFiles/test_arr.dir/build
.PHONY : test_arr/fast

#=============================================================================
# Target rules for targets named test_attq

# Build rule for target.
test_attq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_attq
.PHONY : test_attq

# fast build rule for target.
test_attq/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_attq.dir/build.make tests/CMakeFiles/test_attq.dir/build
.PHONY : test_attq/fast

#=============================================================================
# Target rules for targets named test_blocked_gquic_be

# Build rule for target.
test_blocked_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_blocked_gquic_be
.PHONY : test_blocked_gquic_be

# fast build rule for target.
test_blocked_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_blocked_gquic_be.dir/build.make tests/CMakeFiles/test_blocked_gquic_be.dir/build
.PHONY : test_blocked_gquic_be/fast

#=============================================================================
# Target rules for targets named test_bw_sampler

# Build rule for target.
test_bw_sampler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bw_sampler
.PHONY : test_bw_sampler

# fast build rule for target.
test_bw_sampler/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_bw_sampler.dir/build.make tests/CMakeFiles/test_bw_sampler.dir/build
.PHONY : test_bw_sampler/fast

#=============================================================================
# Target rules for targets named test_conn_close_gquic_be

# Build rule for target.
test_conn_close_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_conn_close_gquic_be
.PHONY : test_conn_close_gquic_be

# fast build rule for target.
test_conn_close_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_conn_close_gquic_be.dir/build.make tests/CMakeFiles/test_conn_close_gquic_be.dir/build
.PHONY : test_conn_close_gquic_be/fast

#=============================================================================
# Target rules for targets named test_crypto_gen

# Build rule for target.
test_crypto_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crypto_gen
.PHONY : test_crypto_gen

# fast build rule for target.
test_crypto_gen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_crypto_gen.dir/build.make tests/CMakeFiles/test_crypto_gen.dir/build
.PHONY : test_crypto_gen/fast

#=============================================================================
# Target rules for targets named test_cubic

# Build rule for target.
test_cubic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cubic
.PHONY : test_cubic

# fast build rule for target.
test_cubic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cubic.dir/build.make tests/CMakeFiles/test_cubic.dir/build
.PHONY : test_cubic/fast

#=============================================================================
# Target rules for targets named test_dec

# Build rule for target.
test_dec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dec
.PHONY : test_dec

# fast build rule for target.
test_dec/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dec.dir/build.make tests/CMakeFiles/test_dec.dir/build
.PHONY : test_dec/fast

#=============================================================================
# Target rules for targets named test_di_nocopy

# Build rule for target.
test_di_nocopy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_di_nocopy
.PHONY : test_di_nocopy

# fast build rule for target.
test_di_nocopy/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_di_nocopy.dir/build.make tests/CMakeFiles/test_di_nocopy.dir/build
.PHONY : test_di_nocopy/fast

#=============================================================================
# Target rules for targets named test_elision

# Build rule for target.
test_elision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_elision
.PHONY : test_elision

# fast build rule for target.
test_elision/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_elision.dir/build.make tests/CMakeFiles/test_elision.dir/build
.PHONY : test_elision/fast

#=============================================================================
# Target rules for targets named test_engine_ctor

# Build rule for target.
test_engine_ctor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_engine_ctor
.PHONY : test_engine_ctor

# fast build rule for target.
test_engine_ctor/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_engine_ctor.dir/build.make tests/CMakeFiles/test_engine_ctor.dir/build
.PHONY : test_engine_ctor/fast

#=============================================================================
# Target rules for targets named test_export_key

# Build rule for target.
test_export_key: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_export_key
.PHONY : test_export_key

# fast build rule for target.
test_export_key/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_export_key.dir/build.make tests/CMakeFiles/test_export_key.dir/build
.PHONY : test_export_key/fast

#=============================================================================
# Target rules for targets named test_frame_chop

# Build rule for target.
test_frame_chop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_frame_chop
.PHONY : test_frame_chop

# fast build rule for target.
test_frame_chop/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_frame_chop.dir/build.make tests/CMakeFiles/test_frame_chop.dir/build
.PHONY : test_frame_chop/fast

#=============================================================================
# Target rules for targets named test_frame_reader

# Build rule for target.
test_frame_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_frame_reader
.PHONY : test_frame_reader

# fast build rule for target.
test_frame_reader/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_frame_reader.dir/build.make tests/CMakeFiles/test_frame_reader.dir/build
.PHONY : test_frame_reader/fast

#=============================================================================
# Target rules for targets named test_frame_writer

# Build rule for target.
test_frame_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_frame_writer
.PHONY : test_frame_writer

# fast build rule for target.
test_frame_writer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_frame_writer.dir/build.make tests/CMakeFiles/test_frame_writer.dir/build
.PHONY : test_frame_writer/fast

#=============================================================================
# Target rules for targets named test_goaway_gquic_be

# Build rule for target.
test_goaway_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_goaway_gquic_be
.PHONY : test_goaway_gquic_be

# fast build rule for target.
test_goaway_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_goaway_gquic_be.dir/build.make tests/CMakeFiles/test_goaway_gquic_be.dir/build
.PHONY : test_goaway_gquic_be/fast

#=============================================================================
# Target rules for targets named test_hkdf

# Build rule for target.
test_hkdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hkdf
.PHONY : test_hkdf

# fast build rule for target.
test_hkdf/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hkdf.dir/build.make tests/CMakeFiles/test_hkdf.dir/build
.PHONY : test_hkdf/fast

#=============================================================================
# Target rules for targets named test_hpi

# Build rule for target.
test_hpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hpi
.PHONY : test_hpi

# fast build rule for target.
test_hpi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hpi.dir/build.make tests/CMakeFiles/test_hpi.dir/build
.PHONY : test_hpi/fast

#=============================================================================
# Target rules for targets named test_lsquic_hash

# Build rule for target.
test_lsquic_hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lsquic_hash
.PHONY : test_lsquic_hash

# fast build rule for target.
test_lsquic_hash/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_lsquic_hash.dir/build.make tests/CMakeFiles/test_lsquic_hash.dir/build
.PHONY : test_lsquic_hash/fast

#=============================================================================
# Target rules for targets named test_packet_out

# Build rule for target.
test_packet_out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_packet_out
.PHONY : test_packet_out

# fast build rule for target.
test_packet_out/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_packet_out.dir/build.make tests/CMakeFiles/test_packet_out.dir/build
.PHONY : test_packet_out/fast

#=============================================================================
# Target rules for targets named test_packet_resize

# Build rule for target.
test_packet_resize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_packet_resize
.PHONY : test_packet_resize

# fast build rule for target.
test_packet_resize/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_packet_resize.dir/build.make tests/CMakeFiles/test_packet_resize.dir/build
.PHONY : test_packet_resize/fast

#=============================================================================
# Target rules for targets named test_packno_len

# Build rule for target.
test_packno_len: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_packno_len
.PHONY : test_packno_len

# fast build rule for target.
test_packno_len/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_packno_len.dir/build.make tests/CMakeFiles/test_packno_len.dir/build
.PHONY : test_packno_len/fast

#=============================================================================
# Target rules for targets named test_parse_packet_in

# Build rule for target.
test_parse_packet_in: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_parse_packet_in
.PHONY : test_parse_packet_in

# fast build rule for target.
test_parse_packet_in/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_parse_packet_in.dir/build.make tests/CMakeFiles/test_parse_packet_in.dir/build
.PHONY : test_parse_packet_in/fast

#=============================================================================
# Target rules for targets named test_purga

# Build rule for target.
test_purga: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_purga
.PHONY : test_purga

# fast build rule for target.
test_purga/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_purga.dir/build.make tests/CMakeFiles/test_purga.dir/build
.PHONY : test_purga/fast

#=============================================================================
# Target rules for targets named test_qlog

# Build rule for target.
test_qlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_qlog
.PHONY : test_qlog

# fast build rule for target.
test_qlog/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_qlog.dir/build.make tests/CMakeFiles/test_qlog.dir/build
.PHONY : test_qlog/fast

#=============================================================================
# Target rules for targets named test_quic_be_floats

# Build rule for target.
test_quic_be_floats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_quic_be_floats
.PHONY : test_quic_be_floats

# fast build rule for target.
test_quic_be_floats/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_quic_be_floats.dir/build.make tests/CMakeFiles/test_quic_be_floats.dir/build
.PHONY : test_quic_be_floats/fast

#=============================================================================
# Target rules for targets named test_reg_pkt_headergen

# Build rule for target.
test_reg_pkt_headergen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_reg_pkt_headergen
.PHONY : test_reg_pkt_headergen

# fast build rule for target.
test_reg_pkt_headergen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_reg_pkt_headergen.dir/build.make tests/CMakeFiles/test_reg_pkt_headergen.dir/build
.PHONY : test_reg_pkt_headergen/fast

#=============================================================================
# Target rules for targets named test_rst_stream_gquic_be

# Build rule for target.
test_rst_stream_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rst_stream_gquic_be
.PHONY : test_rst_stream_gquic_be

# fast build rule for target.
test_rst_stream_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_rst_stream_gquic_be.dir/build.make tests/CMakeFiles/test_rst_stream_gquic_be.dir/build
.PHONY : test_rst_stream_gquic_be/fast

#=============================================================================
# Target rules for targets named test_rtt

# Build rule for target.
test_rtt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rtt
.PHONY : test_rtt

# fast build rule for target.
test_rtt/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_rtt.dir/build.make tests/CMakeFiles/test_rtt.dir/build
.PHONY : test_rtt/fast

#=============================================================================
# Target rules for targets named test_send_headers

# Build rule for target.
test_send_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_send_headers
.PHONY : test_send_headers

# fast build rule for target.
test_send_headers/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_send_headers.dir/build.make tests/CMakeFiles/test_send_headers.dir/build
.PHONY : test_send_headers/fast

#=============================================================================
# Target rules for targets named test_senhist

# Build rule for target.
test_senhist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_senhist
.PHONY : test_senhist

# fast build rule for target.
test_senhist/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_senhist.dir/build.make tests/CMakeFiles/test_senhist.dir/build
.PHONY : test_senhist/fast

#=============================================================================
# Target rules for targets named test_set

# Build rule for target.
test_set: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_set
.PHONY : test_set

# fast build rule for target.
test_set/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_set.dir/build.make tests/CMakeFiles/test_set.dir/build
.PHONY : test_set/fast

#=============================================================================
# Target rules for targets named test_sfcw

# Build rule for target.
test_sfcw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sfcw
.PHONY : test_sfcw

# fast build rule for target.
test_sfcw/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sfcw.dir/build.make tests/CMakeFiles/test_sfcw.dir/build
.PHONY : test_sfcw/fast

#=============================================================================
# Target rules for targets named test_shi

# Build rule for target.
test_shi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shi
.PHONY : test_shi

# fast build rule for target.
test_shi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_shi.dir/build.make tests/CMakeFiles/test_shi.dir/build
.PHONY : test_shi/fast

#=============================================================================
# Target rules for targets named test_spi

# Build rule for target.
test_spi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_spi
.PHONY : test_spi

# fast build rule for target.
test_spi/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_spi.dir/build.make tests/CMakeFiles/test_spi.dir/build
.PHONY : test_spi/fast

#=============================================================================
# Target rules for targets named test_stop_waiting_gquic_be

# Build rule for target.
test_stop_waiting_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stop_waiting_gquic_be
.PHONY : test_stop_waiting_gquic_be

# fast build rule for target.
test_stop_waiting_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_stop_waiting_gquic_be.dir/build.make tests/CMakeFiles/test_stop_waiting_gquic_be.dir/build
.PHONY : test_stop_waiting_gquic_be/fast

#=============================================================================
# Target rules for targets named test_streamgen

# Build rule for target.
test_streamgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_streamgen
.PHONY : test_streamgen

# fast build rule for target.
test_streamgen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_streamgen.dir/build.make tests/CMakeFiles/test_streamgen.dir/build
.PHONY : test_streamgen/fast

#=============================================================================
# Target rules for targets named test_streamparse

# Build rule for target.
test_streamparse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_streamparse
.PHONY : test_streamparse

# fast build rule for target.
test_streamparse/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_streamparse.dir/build.make tests/CMakeFiles/test_streamparse.dir/build
.PHONY : test_streamparse/fast

#=============================================================================
# Target rules for targets named test_tokgen

# Build rule for target.
test_tokgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tokgen
.PHONY : test_tokgen

# fast build rule for target.
test_tokgen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tokgen.dir/build.make tests/CMakeFiles/test_tokgen.dir/build
.PHONY : test_tokgen/fast

#=============================================================================
# Target rules for targets named test_trapa

# Build rule for target.
test_trapa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_trapa
.PHONY : test_trapa

# fast build rule for target.
test_trapa/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_trapa.dir/build.make tests/CMakeFiles/test_trapa.dir/build
.PHONY : test_trapa/fast

#=============================================================================
# Target rules for targets named test_varint

# Build rule for target.
test_varint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_varint
.PHONY : test_varint

# fast build rule for target.
test_varint/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_varint.dir/build.make tests/CMakeFiles/test_varint.dir/build
.PHONY : test_varint/fast

#=============================================================================
# Target rules for targets named test_ver_nego

# Build rule for target.
test_ver_nego: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ver_nego
.PHONY : test_ver_nego

# fast build rule for target.
test_ver_nego/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ver_nego.dir/build.make tests/CMakeFiles/test_ver_nego.dir/build
.PHONY : test_ver_nego/fast

#=============================================================================
# Target rules for targets named test_wuf_gquic_be

# Build rule for target.
test_wuf_gquic_be: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_wuf_gquic_be
.PHONY : test_wuf_gquic_be

# fast build rule for target.
test_wuf_gquic_be/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_wuf_gquic_be.dir/build.make tests/CMakeFiles/test_wuf_gquic_be.dir/build
.PHONY : test_wuf_gquic_be/fast

#=============================================================================
# Target rules for targets named test_frame_rw

# Build rule for target.
test_frame_rw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_frame_rw
.PHONY : test_frame_rw

# fast build rule for target.
test_frame_rw/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_frame_rw.dir/build.make tests/CMakeFiles/test_frame_rw.dir/build
.PHONY : test_frame_rw/fast

#=============================================================================
# Target rules for targets named test_ack_merge

# Build rule for target.
test_ack_merge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ack_merge
.PHONY : test_ack_merge

# fast build rule for target.
test_ack_merge/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ack_merge.dir/build.make tests/CMakeFiles/test_ack_merge.dir/build
.PHONY : test_ack_merge/fast

#=============================================================================
# Target rules for targets named test_hcsi_reader

# Build rule for target.
test_hcsi_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hcsi_reader
.PHONY : test_hcsi_reader

# fast build rule for target.
test_hcsi_reader/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hcsi_reader.dir/build.make tests/CMakeFiles/test_hcsi_reader.dir/build
.PHONY : test_hcsi_reader/fast

#=============================================================================
# Target rules for targets named test_h3_framing

# Build rule for target.
test_h3_framing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_h3_framing
.PHONY : test_h3_framing

# fast build rule for target.
test_h3_framing/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_h3_framing.dir/build.make tests/CMakeFiles/test_h3_framing.dir/build
.PHONY : test_h3_framing/fast

#=============================================================================
# Target rules for targets named test_stream

# Build rule for target.
test_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stream
.PHONY : test_stream

# fast build rule for target.
test_stream/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_stream.dir/build.make tests/CMakeFiles/test_stream.dir/build
.PHONY : test_stream/fast

#=============================================================================
# Target rules for targets named graph_cubic

# Build rule for target.
graph_cubic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_cubic
.PHONY : graph_cubic

# fast build rule for target.
graph_cubic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/graph_cubic.dir/build.make tests/CMakeFiles/graph_cubic.dir/build
.PHONY : graph_cubic/fast

#=============================================================================
# Target rules for targets named mini_parse

# Build rule for target.
mini_parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mini_parse
.PHONY : mini_parse

# fast build rule for target.
mini_parse/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/mini_parse.dir/build.make tests/CMakeFiles/mini_parse.dir/build
.PHONY : mini_parse/fast

#=============================================================================
# Target rules for targets named test_min_heap

# Build rule for target.
test_min_heap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_min_heap
.PHONY : test_min_heap

# fast build rule for target.
test_min_heap/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_min_heap.dir/build.make tests/CMakeFiles/test_min_heap.dir/build
.PHONY : test_min_heap/fast

#=============================================================================
# Target rules for targets named test_malo_pooled

# Build rule for target.
test_malo_pooled: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_malo_pooled
.PHONY : test_malo_pooled

# fast build rule for target.
test_malo_pooled/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_malo_pooled.dir/build.make tests/CMakeFiles/test_malo_pooled.dir/build
.PHONY : test_malo_pooled/fast

#=============================================================================
# Target rules for targets named test_malo_nopool

# Build rule for target.
test_malo_nopool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_malo_nopool
.PHONY : test_malo_nopool

# fast build rule for target.
test_malo_nopool/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_malo_nopool.dir/build.make tests/CMakeFiles/test_malo_nopool.dir/build
.PHONY : test_malo_nopool/fast

#=============================================================================
# Target rules for targets named test_minmax

# Build rule for target.
test_minmax: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_minmax
.PHONY : test_minmax

# fast build rule for target.
test_minmax/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_minmax.dir/build.make tests/CMakeFiles/test_minmax.dir/build
.PHONY : test_minmax/fast

#=============================================================================
# Target rules for targets named test_rechist

# Build rule for target.
test_rechist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rechist
.PHONY : test_rechist

# fast build rule for target.
test_rechist/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_rechist.dir/build.make tests/CMakeFiles/test_rechist.dir/build
.PHONY : test_rechist/fast

#=============================================================================
# Target rules for targets named test_trechist

# Build rule for target.
test_trechist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_trechist
.PHONY : test_trechist

# fast build rule for target.
test_trechist/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_trechist.dir/build.make tests/CMakeFiles/test_trechist.dir/build
.PHONY : test_trechist/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... art_server"
	@echo "... duck_client"
	@echo "... duck_server"
	@echo "... echo_client"
	@echo "... echo_server"
	@echo "... graph_cubic"
	@echo "... http_client"
	@echo "... http_server"
	@echo "... lsquic"
	@echo "... md5_client"
	@echo "... md5_server"
	@echo "... mini_parse"
	@echo "... perf_client"
	@echo "... perf_server"
	@echo "... test_ack"
	@echo "... test_ack_merge"
	@echo "... test_ackgen_gquic_be"
	@echo "... test_ackparse_gquic_be"
	@echo "... test_ackparse_ietf"
	@echo "... test_alarmset"
	@echo "... test_alt_svc_ver"
	@echo "... test_arr"
	@echo "... test_attq"
	@echo "... test_blocked_gquic_be"
	@echo "... test_bw_sampler"
	@echo "... test_conn_close_gquic_be"
	@echo "... test_crypto_gen"
	@echo "... test_cubic"
	@echo "... test_dec"
	@echo "... test_di_nocopy"
	@echo "... test_elision"
	@echo "... test_engine_ctor"
	@echo "... test_export_key"
	@echo "... test_frame_chop"
	@echo "... test_frame_reader"
	@echo "... test_frame_rw"
	@echo "... test_frame_writer"
	@echo "... test_goaway_gquic_be"
	@echo "... test_h3_framing"
	@echo "... test_hcsi_reader"
	@echo "... test_hkdf"
	@echo "... test_hpi"
	@echo "... test_lsquic_hash"
	@echo "... test_malo_nopool"
	@echo "... test_malo_pooled"
	@echo "... test_min_heap"
	@echo "... test_minmax"
	@echo "... test_packet_out"
	@echo "... test_packet_resize"
	@echo "... test_packno_len"
	@echo "... test_parse_packet_in"
	@echo "... test_purga"
	@echo "... test_qlog"
	@echo "... test_quic_be_floats"
	@echo "... test_rechist"
	@echo "... test_reg_pkt_headergen"
	@echo "... test_rst_stream_gquic_be"
	@echo "... test_rtt"
	@echo "... test_send_headers"
	@echo "... test_senhist"
	@echo "... test_set"
	@echo "... test_sfcw"
	@echo "... test_shi"
	@echo "... test_spi"
	@echo "... test_stop_waiting_gquic_be"
	@echo "... test_stream"
	@echo "... test_streamgen"
	@echo "... test_streamparse"
	@echo "... test_tokgen"
	@echo "... test_trapa"
	@echo "... test_trechist"
	@echo "... test_varint"
	@echo "... test_ver_nego"
	@echo "... test_wuf_gquic_be"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

