# CMake generated Testfile for 
# Source directory: /home/ubuntu/quic-art/tests
# Build directory: /home/ubuntu/quic-art/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ack]=] "test_ack")
set_tests_properties([=[ack]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[ackgen_gquic_be]=] "test_ackgen_gquic_be")
set_tests_properties([=[ackgen_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[ackparse_gquic_be]=] "test_ackparse_gquic_be")
set_tests_properties([=[ackparse_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[ackparse_ietf]=] "test_ackparse_ietf")
set_tests_properties([=[ackparse_ietf]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[alarmset]=] "test_alarmset")
set_tests_properties([=[alarmset]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[alt_svc_ver]=] "test_alt_svc_ver")
set_tests_properties([=[alt_svc_ver]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[arr]=] "test_arr")
set_tests_properties([=[arr]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[attq]=] "test_attq")
set_tests_properties([=[attq]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[blocked_gquic_be]=] "test_blocked_gquic_be")
set_tests_properties([=[blocked_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[bw_sampler]=] "test_bw_sampler")
set_tests_properties([=[bw_sampler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[conn_close_gquic_be]=] "test_conn_close_gquic_be")
set_tests_properties([=[conn_close_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[crypto_gen]=] "test_crypto_gen")
set_tests_properties([=[crypto_gen]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[cubic]=] "test_cubic")
set_tests_properties([=[cubic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[dec]=] "test_dec")
set_tests_properties([=[dec]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[di_nocopy]=] "test_di_nocopy")
set_tests_properties([=[di_nocopy]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[elision]=] "test_elision")
set_tests_properties([=[elision]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[engine_ctor]=] "test_engine_ctor")
set_tests_properties([=[engine_ctor]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[export_key]=] "test_export_key")
set_tests_properties([=[export_key]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[frame_chop]=] "test_frame_chop")
set_tests_properties([=[frame_chop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[frame_reader]=] "test_frame_reader")
set_tests_properties([=[frame_reader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[frame_writer]=] "test_frame_writer")
set_tests_properties([=[frame_writer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[goaway_gquic_be]=] "test_goaway_gquic_be")
set_tests_properties([=[goaway_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[hkdf]=] "test_hkdf")
set_tests_properties([=[hkdf]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[hpi]=] "test_hpi")
set_tests_properties([=[hpi]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[lsquic_hash]=] "test_lsquic_hash")
set_tests_properties([=[lsquic_hash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[packet_out]=] "test_packet_out")
set_tests_properties([=[packet_out]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[packet_resize]=] "test_packet_resize")
set_tests_properties([=[packet_resize]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[packno_len]=] "test_packno_len")
set_tests_properties([=[packno_len]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[parse_packet_in]=] "test_parse_packet_in")
set_tests_properties([=[parse_packet_in]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[purga]=] "test_purga")
set_tests_properties([=[purga]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[qlog]=] "test_qlog")
set_tests_properties([=[qlog]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[quic_be_floats]=] "test_quic_be_floats")
set_tests_properties([=[quic_be_floats]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[reg_pkt_headergen]=] "test_reg_pkt_headergen")
set_tests_properties([=[reg_pkt_headergen]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[rst_stream_gquic_be]=] "test_rst_stream_gquic_be")
set_tests_properties([=[rst_stream_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[rtt]=] "test_rtt")
set_tests_properties([=[rtt]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[send_headers]=] "test_send_headers")
set_tests_properties([=[send_headers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[senhist]=] "test_senhist")
set_tests_properties([=[senhist]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[set]=] "test_set")
set_tests_properties([=[set]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[sfcw]=] "test_sfcw")
set_tests_properties([=[sfcw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[shi]=] "test_shi")
set_tests_properties([=[shi]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[spi]=] "test_spi")
set_tests_properties([=[spi]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[stop_waiting_gquic_be]=] "test_stop_waiting_gquic_be")
set_tests_properties([=[stop_waiting_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[streamgen]=] "test_streamgen")
set_tests_properties([=[streamgen]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[streamparse]=] "test_streamparse")
set_tests_properties([=[streamparse]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[tokgen]=] "test_tokgen")
set_tests_properties([=[tokgen]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[trapa]=] "test_trapa")
set_tests_properties([=[trapa]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[varint]=] "test_varint")
set_tests_properties([=[varint]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[ver_nego]=] "test_ver_nego")
set_tests_properties([=[ver_nego]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[wuf_gquic_be]=] "test_wuf_gquic_be")
set_tests_properties([=[wuf_gquic_be]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[frame_rw]=] "test_frame_rw")
set_tests_properties([=[frame_rw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[ack_merge]=] "test_ack_merge")
set_tests_properties([=[ack_merge]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[hcsi_reader]=] "test_hcsi_reader")
set_tests_properties([=[hcsi_reader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[h3_framing]=] "test_h3_framing")
set_tests_properties([=[h3_framing]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;110;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[stream]=] "test_stream")
set_tests_properties([=[stream]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;118;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[stream_hash]=] "test_stream" "-h")
set_tests_properties([=[stream_hash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;119;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[stream_A]=] "test_stream" "-A")
set_tests_properties([=[stream_A]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;120;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[stream_hash_A]=] "test_stream" "-A" "-h")
set_tests_properties([=[stream_hash_A]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;121;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[min_heap]=] "test_min_heap")
set_tests_properties([=[min_heap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;132;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[malo_pooled]=] "test_malo_pooled")
set_tests_properties([=[malo_pooled]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;141;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[malo_nopool]=] "test_malo_nopool")
set_tests_properties([=[malo_nopool]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;149;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[minmax]=] "test_minmax")
set_tests_properties([=[minmax]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;155;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[rechist]=] "test_rechist")
set_tests_properties([=[rechist]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;158;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
add_test([=[trechist]=] "test_trechist")
set_tests_properties([=[trechist]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/quic-art/tests/CMakeLists.txt;161;ADD_TEST;/home/ubuntu/quic-art/tests/CMakeLists.txt;0;")
